CREATE DATABASE IF NOT EXISTS MENU_DIGITAL;
USE MENU_DIGITAL;

CREATE TABLE IF NOT EXISTS USUARIOS_ADMIN (
ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_USUARIO VARCHAR(100) NOT NULL,
CORREO VARCHAR(150) NOT NULL UNIQUE,
CONTRASENA VARCHAR(255) NOT NULL,
ROL ENUM('ADMIN', 'SUPERADMIN') DEFAULT 'ADMIN',
ESTADO ENUM('ACTIVO', 'INACTIVO') DEFAULT 'ACTIVO',
FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CATEGORIAS(
ID_CATERGORIAS INT AUTO_INCREMENT PRIMARY KEY,
IMAGEN VARCHAR(1000),
NOMBRE_CATE VARCHAR(300) NOT NULL,
ESTADO_CATE ENUM('DISPONIBLE', 'NO DISPONIBLE') DEFAULT 'DISPONIBLE'
);

CREATE TABLE IF NOT EXISTS SUBCATEGORIAS(
ID_SUBCATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
IMAGEN VARCHAR(1000),
NOMBRE_SUBCATE VARCHAR(300) NOT NULL,
ESTADO_SUBCATE ENUM('DISPONIBLE','NO DISPONIBLE') DEFAULT 'DISPONIBLE',
ID_CATEGO INT NOT NULL,
FOREIGN KEY (ID_CATEGO) REFERENCES CATEGORIAS (ID_CATERGORIAS) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PRODUCTOS(
ID_PRODUCTOS INT AUTO_INCREMENT PRIMARY KEY,
IMAGEN VARCHAR(1000),
NOMBRE_PRODUCTO VARCHAR(300) NOT NULL,
DESCRIPCION_PRO VARCHAR(2000),
ESDADO_PRO ENUM('DISPONIBLE','NO DISPONIBLE') DEFAULT 'DISPONIBLE',
PRECIO_PRO DECIMAL(10,2) NOT NULL,
ID_SUBCATE INT NOT NULL,
FOREIGN KEY (ID_SUBCATE) REFERENCES SUBCATEGORIAS (ID_SUBCATEGORIA) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MESAS (
ID_MESAS INT AUTO_INCREMENT PRIMARY KEY,
NUMERO_MESA INT NOT NULL UNIQUE,
ESTADO_MESA ENUM('DISPONIBLE','OCUPADA','PAGANDO') DEFAULT 'DISPONIBLE'
); 

CREATE TABLE IF NOT EXISTS PEDIDOS(
ID_PEDIDOS INT AUTO_INCREMENT PRIMARY KEY,
FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
ESTADO_PEDIDO ENUM('PENDIENTE','EN_PREPARACION','CANCELADO','ENTREGADO') DEFAULT 'PENDIENTE',
ID_MESA INT,
FOREIGN KEY (ID_MESA) REFERENCES MESAS (ID_MESAS)
);

CREATE TABLE IF NOT EXISTS DETALLE_PEDIDO(
ID_DETALLE_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
CANTIDAD INT NOT NULL DEFAULT 1,
PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
ID_PRODUCT INT NOT NULL,
ID_PEDID INT NOT NULL,
FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTOS (ID_PRODUCTOS),
FOREIGN KEY (ID_PEDID) REFERENCES PEDIDOS (ID_PEDIDOS)
);