-- ==========================================================
-- SCRIPT UNIFICADO: MENU_DIGITAL (PRODUCCIÓN)
-- ==========================================================

CREATE DATABASE IF NOT EXISTS MENU_DIGITAL;
USE MENU_DIGITAL;

-- 1. TABLA: USUARIOS_ADMIN
CREATE TABLE IF NOT EXISTS USUARIOS_ADMIN (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_USUARIO VARCHAR(100) NOT NULL,
    CORREO VARCHAR(150) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(255) NOT NULL,
    ROL ENUM('ADMIN', 'SUPERADMIN') DEFAULT 'ADMIN',
    ESTADO ENUM('ACTIVO', 'INACTIVO') DEFAULT 'ACTIVO',
    FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 2. TABLA: CATEGORIAS
CREATE TABLE IF NOT EXISTS CATEGORIAS (
    ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    IMAGEN VARCHAR(1000),
    NOMBRE_CATE VARCHAR(300) NOT NULL,
    ESTADO_CATE ENUM('DISPONIBLE', 'NO DISPONIBLE') DEFAULT 'DISPONIBLE'
);

-- 3. TABLA: SUBCATEGORIAS
CREATE TABLE IF NOT EXISTS SUBCATEGORIAS (
    ID_SUBCATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    IMAGEN VARCHAR(1000),
    NOMBRE_SUBCATE VARCHAR(300) NOT NULL,
    ESTADO_SUBCATE ENUM('DISPONIBLE','NO DISPONIBLE') DEFAULT 'DISPONIBLE',
    ID_CATEGO INT NOT NULL,
    CONSTRAINT fk_sub_cate FOREIGN KEY (ID_CATEGO) REFERENCES CATEGORIAS (ID_CATEGORIA) ON DELETE CASCADE
);

-- 4. TABLA: PRODUCTOS
CREATE TABLE IF NOT EXISTS PRODUCTOS (
    ID_PRODUCTOS INT AUTO_INCREMENT PRIMARY KEY,
    IMAGEN VARCHAR(1000),
    NOMBRE_PRODUCTO VARCHAR(300) NOT NULL,
    DESCRIPCION_PRO VARCHAR(2000),
    ESTADO_PRO ENUM('DISPONIBLE','NO DISPONIBLE') DEFAULT 'DISPONIBLE',
    PRECIO_PRO DECIMAL(10,2) NOT NULL,
    ID_SUBCATE INT NOT NULL,
    CONSTRAINT fk_prod_sub FOREIGN KEY (ID_SUBCATE) REFERENCES SUBCATEGORIAS (ID_SUBCATEGORIA) ON DELETE CASCADE
);

-- 5. TABLA: MESAS (Incluye ULTIMA_SESION y estado ELIMINADA para borrado lógico)
CREATE TABLE IF NOT EXISTS MESAS (
    ID_MESAS INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO_MESA INT NOT NULL UNIQUE,
    ESTADO_MESA ENUM(
        'DISPONIBLE', 'OCUPADA', 'SOLICITO CUENTA', 'LLAMANDO MESERO', 
        'ESPERANDO PEDIDO', 'PAGANDO', 'ENTREGADO', 'RECIBIDO', 'ELIMINADA'
    ) DEFAULT 'DISPONIBLE',
    ULTIMA_SESION DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 6. TABLA: PEDIDOS (Con RESTRICT para proteger historial contable)
CREATE TABLE IF NOT EXISTS PEDIDOS (
    ID_PEDIDOS INT AUTO_INCREMENT PRIMARY KEY,
    FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
    ESTADO_PEDIDO ENUM('PENDIENTE','EN_PREPARACION','CANCELADO','ENTREGADO') DEFAULT 'PENDIENTE',
    ID_MESA INT,
    CONSTRAINT fk_pedidos_mesa FOREIGN KEY (ID_MESA) REFERENCES MESAS (ID_MESAS) ON DELETE RESTRICT
);

-- 7. TABLA: DETALLE_PEDIDO (Corregido ID_PRODCUT a ID_PRODUCT)
CREATE TABLE IF NOT EXISTS DETALLE_PEDIDO (
    ID_DETALLE_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    CANTIDAD INT NOT NULL DEFAULT 1,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    ID_PRODUCT INT NOT NULL,
    ID_PEDID INT NOT NULL,
    OBSERVACIONES VARCHAR(500) DEFAULT NULL,
    CONSTRAINT fk_detalle_prod FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTOS (ID_PRODUCTOS),
    CONSTRAINT fk_detalle_pedid FOREIGN KEY (ID_PEDID) REFERENCES PEDIDOS (ID_PEDIDOS) ON DELETE CASCADE
);

-- 8. TABLA: FEEDBACK
CREATE TABLE IF NOT EXISTS FEEDBACK (
    ID_FEEDBACK INT AUTO_INCREMENT PRIMARY KEY,
    ID_MESA_REF INT, -- Cambiado a INT para integridad con MESAS
    ESTRELLAS INT NOT NULL,
    COMENTARIO TEXT,
    FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_feedback_mesa FOREIGN KEY (ID_MESA_REF) REFERENCES MESAS (ID_MESAS) ON DELETE CASCADE
);

-- INSERCIÓN DE DATOS INICIALES

INSERT INTO USUARIOS_ADMIN (NOMBRE_USUARIO, CORREO, CONTRASENA, ROL, ESTADO) 
VALUES ('alex_gerente', 'alexmartinez@balcony.com', 'alexadmin', 'SUPERADMIN', 'ACTIVO');
